// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClbCzZCKFPSbs3CFBUiEz8DBlfIMjcFvc',
    appId: '1:133060069069:web:a52c38faa47d2befb24b84',
    messagingSenderId: '133060069069',
    projectId: 'dashboard2-a3fdd',
    authDomain: 'dashboard2-a3fdd.firebaseapp.com',
    storageBucket: 'dashboard2-a3fdd.appspot.com',
    measurementId: 'G-4THQG6J01C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdTfNjHNVSIMdXU1d-ul9f1sYghOXSpE4',
    appId: '1:133060069069:android:502b98d8f459011fb24b84',
    messagingSenderId: '133060069069',
    projectId: 'dashboard2-a3fdd',
    storageBucket: 'dashboard2-a3fdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5cGx8wPG36xX8aOwMjvL_qX0PdBZ9moU',
    appId: '1:133060069069:ios:2b3e31b6c1560a49b24b84',
    messagingSenderId: '133060069069',
    projectId: 'dashboard2-a3fdd',
    storageBucket: 'dashboard2-a3fdd.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5cGx8wPG36xX8aOwMjvL_qX0PdBZ9moU',
    appId: '1:133060069069:ios:6a0cecec41ed58d9b24b84',
    messagingSenderId: '133060069069',
    projectId: 'dashboard2-a3fdd',
    storageBucket: 'dashboard2-a3fdd.appspot.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
